### ISSUE TITLE
Supplementary Material

### ISSUE THREAD

**Issue by samleoqh** [LemuelPuglisi/BrLP#1]
Hi,
Thanks a lot for sharing this great work. I just wondering where can I find the  Supplementary Material that contains training details. 
Best.

**Comment by LemuelPuglisi** [comment]
Hi! You can find the supplementary material here: https://papers.miccai.org/miccai-2024/289-Paper0511.html

Please reach me at lemuel.puglisi (AT) phd.unict.it if you need anything else :)
